export const GIB_BIRIM_KODLARI = [
    { kod: 'ADET', ad: 'Adet/Unit' },
    { kod: 'KG', ad: 'Kilogram' },
    { kod: 'MTR', ad: 'Metre' },
    { kod: 'LTR', ad: 'Litre' },
    { kod: 'GRM', ad: 'Gram' },
    { kod: 'MLT', ad: 'Mililitre' },
    { kod: 'PK', ad: 'Paket' },
    { kod: 'SET', ad: 'Set/Takım' },
    { kod: 'BOX', ad: 'Kutu/Koli' },
    { kod: 'DM3', ad: 'Desimetreküp' },
    { kod: 'CM3', ad: 'Santimetreküp' },
    { kod: 'MTK', ad: 'Metrekare' },
    { kod: 'CT', ad: 'Karat' },
    { kod: 'KWH', ad: 'Kilowattsaat' },
    { kod: 'MIN', ad: 'Dakika' },
    { kod: 'HUR', ad: 'Saat' },
    { kod: 'DAY', ad: 'Gün' },
    { kod: 'WEE', ad: 'Hafta' },
    { kod: 'MON', ad: 'Ay' },
    { kod: 'ANN', ad: 'Yıl' },
];
