export enum OrderType {
    SALE = 'SALE',
    PURCHASE = 'PURCHASE'
}

export enum SalesOrderStatus {
    PENDING = 'PENDING',
    PREPARING = 'PREPARING',
    PREPARED = 'PREPARED',
    SHIPPED = 'SHIPPED',
    PARTIALLY_SHIPPED = 'PARTIALLY_SHIPPED',
    INVOICED = 'INVOICED',
    CANCELLED = 'CANCELLED'
}
