export enum WorkOrderStatus {
    WAITING_DIAGNOSIS = 'WAITING_DIAGNOSIS',
    PENDING_APPROVAL = 'PENDING_APPROVAL',
    APPROVED_IN_PROGRESS = 'APPROVED_IN_PROGRESS',
    PART_WAITING = 'PART_WAITING',
    PARTS_SUPPLIED = 'PARTS_SUPPLIED',
    VEHICLE_READY = 'VEHICLE_READY',
    INVOICED_CLOSED = 'INVOICED_CLOSED',
    CLOSED_WITHOUT_INVOICE = 'CLOSED_WITHOUT_INVOICE',
    CANCELLED = 'CANCELLED'
}

export enum VehicleWorkflowStatus {
    WAITING = 'WAITING',
    IN_PROGRESS = 'IN_PROGRESS',
    READY = 'READY',
    DELIVERED = 'DELIVERED'
}

export enum PartWorkflowStatus {
    NOT_STARTED = 'NOT_STARTED',
    PARTS_SUPPLIED_DIRECT = 'PARTS_SUPPLIED_DIRECT',
    PARTS_PENDING = 'PARTS_PENDING',
    PARTIALLY_SUPPLIED = 'PARTIALLY_SUPPLIED',
    ALL_PARTS_SUPPLIED = 'ALL_PARTS_SUPPLIED'
}
