export const turkiyeBankalari = [
  'Ziraat Bankası',
  'Garanti BBVA',
  'İş Bankası',
  'Yapı Kredi',
  'Akbank',
  'Halkbank',
  'Vakıfbank',
  'QNB Finansbank',
  'Denizbank',
  'TEB',
  'ING Bank',
  'Kuveyt Türk',
  'Türkiye Finans',
  'Albaraka Türk',
  'Vakıf Katılım',
  'Ziraat Katılım',
  'HSBC',
  'Alternatif Bank',
  'Burgan Bank',
  'Odeabank',
  'Şekerbank',
  'Turkish Bank',
  'Fibabanka',
  'ICBC Turkey',
  'Anadolubank',
];

export const kartTipleri = [
  'Visa',
  'MasterCard',
  'Troy',
  'American Express',
];

